version: "1.0"
info:
  model: int-scaffold
packages:
- name: SesmProject
  gitServerName: Adapters
  gitUrl: https://github.com/Sephali-Smrutisikha-IBM-1
  gitUsername: Sephali-Smrutisikha-IBM-1
  gitBranch: main
- name: WmKafkaAdapter
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
  wpmVersion: latest
